###############################################
# ReadTheDocs Configuration                   #
# (.readthedocs.yml)                          #
# Adapted from https://github.com/pybel/pybel #
###############################################

# For more information, see: https://docs.readthedocs.io/en/latest/yaml-config.html
python:
  version: 3
  pip_install: true
  extra_requirements:
    - docs
