###############################################
# Travis-CI Configuration                     #
# (.travis.yml)                               #
# Adapted from https://github.com/pybel/pybel #
###############################################
cache: pip
language: python
python: "3.8"
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - tox -e coverage-report
  - codecov
